---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: static-default
    #namespace: vault-secrets-operator
  namespace: vault-secrets-operator
spec:
  #address: http://vault.vault.svc.cluster.local:8200
  address: http://vaultkns1.kns1.svc.cluster.local:8200
  skipTLSVerify: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-demo
  namespace: tenant-1
spec:
  vaultConnectionRef: vault-secrets-operator/static-default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: static-demo
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: tenant-1
  name: static-demo
spec:
  # namespace: cluster1/tenant-1
  vaultAuthRef: static-demo
  mount: kvv2
  type: kv-v2
  path: secret
  refreshAfter: 5s
  destination:
    name: secret1
    create: true
  rolloutRestartTargets:
  - kind: Deployment
    name: static-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-demo
  namespace: tenant-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-demo
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: static-demo
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.19.6-alpine
        volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret1
          optional: false # default setting; "mysecret" must exist

